{"uid":"2f95de1d38b0d989","name":"test_edit_contact_field_unknow","fullName":"test.Contactos.test_edit_contact#test_edit_contact_field_unknow","historyId":"5fd0fa2d9ca4dcf74ebc4c06395d5ee4","time":{"start":1728601261290,"stop":1728601261291,"duration":1},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nTypeError: create_contact_data() got an unexpected keyword argument 'test'","statusTrace":"setup_edit_contact = ({'Espo-Authorization': 'YWRtaW46NjI0MjkyNTU=', 'X-Api-Key': 'f542db99f09e823eeb14cd558f104fef'}, {'accountIsInactive': None, 'accountName': None, 'accountsColumns': {}, 'accountsIds': [], ...})\n\n    @pytest.mark.regression\n    @pytest.mark.functional\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_edit_contact_field_unknow(setup_edit_contact):\n        headers, contact = setup_edit_contact\n>       data = create_contact_data(salutationName=\"Ms.\", firstName=\"Mike\",\n                                                             lastName=\"Towel\",\n                                                             test=\"test\",\n                                                             addressPostalCode=\"0000\", addressStreet=\"none\",\n                                                             addressState=\"none\", addressCity=\"none\", addressCountry=\"none\",)\nE       TypeError: create_contact_data() got an unexpected keyword argument 'test'\n\ntest/Contactos/test_edit_contact.py:44: TypeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1728601253282,"stop":1728601253283,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"get_headers","time":{"start":1728601253283,"stop":1728601253283,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_edit_contact","time":{"start":1728601261027,"stop":1728601261290,"duration":263},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[{"name":"setup_edit_contact::0","time":{"start":1728601261294,"stop":1728601261468,"duration":174},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"functional"},{"name":"tag","value":"regression"},{"name":"parentSuite","value":"test.Contactos"},{"name":"suite","value":"test_edit_contact"},{"name":"host","value":"fv-az1432-961"},{"name":"thread","value":"2163-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.Contactos.test_edit_contact"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["functional","regression","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"2f95de1d38b0d989.json","parameterValues":[]}